Separate things that aren't test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -62,11 +62,12 @@ before_script:
       sh -e /etc/init.d/xvfb start;
       sleep 3;
     fi
+  # inline must be run twice to clear out compiler warnings
+  # we don't care if it fails the first time
+  - if [[ ! -z "${FIPY_INLINE}" ]]; then
+      $MPIRUN python setup.py test || true;
+    fi
 script:
- # inline must be run twice to clear out compiler warnings
- # we don't care if it fails the first time
- - if [[ ! -z "${FIPY_INLINE}" ]]; then
-     travis_wait $MPIRUN python setup.py test > /dev/null 2>&1 || true;
-   fi
- - $MPIRUN python setup.py test;
- - conda env export
+  - $MPIRUN python setup.py test;
+after_success:
+  - conda env export
