restore regular .travis.yml, but keep .travis-nix.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,22 +1,69 @@
 # inspired by http://conda.pydata.org/docs/travis.html
 #
 # language: python causes grief on osx
-language: nix
+language: generic
 os:
    - osx
+  # - linux
 env:
-  - TRAVIS_PYTHON_VERSION=3.6 FIPY_SOLVERS=scipy
-cache:
-  directories:
-    - $STORE
+  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=pysparse
+#  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=pysparse FIPY_INLINE=1
+  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=scipy
+  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=trilinos
+  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN="mpirun -np 2" FIPY_SOLVERS=trilinos
+  - TRAVIS_PYTHON_VERSION=3.6 MPIRUN= FIPY_SOLVERS=scipy
+cache: apt
+branches:
+  except:
+    - nist-pages
 before_install:
-  - sudo mkdir -p /etc/nix
-  - echo "binary-caches = https://cache.nixos.org/ file://$STORE" | sudo tee -a /etc/nix/nix.conf > /dev/null
-  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
-before_cache:
-  - mkdir -p $STORE
-  - nix copy --to file://$STORE -f shell.nix buildInputs
+  # sudo ln -s /usr/lib/lapack/liblapack.so.3gf /usr/lib/lapack/liblapack.so.3;
+  # sudo ldconfig;
+  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
+      sudo apt-get update;
+    fi
+  # We do this conditionally because it saves us some downloading if the
+  # version is the same.
+  - PY3K=$(echo "$TRAVIS_PYTHON_VERSION >= 3.0" | bc)
+  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
+      export MINICONDA_OS_NAME=Linux;
+    elif [[ $TRAVIS_OS_NAME = "osx" ]]; then
+      export MINICONDA_OS_NAME=MacOSX;
+    fi
+  - if [[ $PY3K -eq 1 ]]; then
+      export MINICONDA_VERSION=3;
+    else
+      export MINICONDA_VERSION=2;
+    fi
+  - wget https://repo.continuum.io/miniconda/Miniconda${MINICONDA_VERSION}-latest-${MINICONDA_OS_NAME}-x86_64.sh -O miniconda.sh;
+  - bash miniconda.sh -b -p $HOME/miniconda
+  - export PATH="$HOME/miniconda/bin:$PATH"
+  - hash -r
+  - conda config --set always_yes yes --set changeps1 no
+  - conda update -q conda
+  - conda create --quiet --name test-environment --show-channel-urls --channel conda-forge --only-deps python=$TRAVIS_PYTHON_VERSION fipy;
+  - source activate test-environment
+  # Useful for debugging any issues with conda
+  - conda info -a
+  - pip install future
+  - pip install scikit-fmm
 install:
-  - nix-shell --pure --command "echo 'run nix-shell and exit'"
+  - python setup.py install
+before_script:
+  # lack of display causes tests to abort at VtkViewer
+  # Workaround @ http://docs.enthought.com/mayavi/mayavi/tips.html#rendering-using-the-virtual-framebuffer
+  # and https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
+  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
+      export DISPLAY=:99.0;
+      sh -e /etc/init.d/xvfb start;
+      sleep 3;
+    fi
+  # inline must be run twice to clear out compiler warnings
+  # we don't care if it fails the first time
+  - if [[ ! -z "${FIPY_INLINE}" ]]; then
+      travis_wait 40 $MPIRUN python setup.py test || true;
+    fi
 script:
-  - nix-shell --command "python setup.py test";
+  - $MPIRUN python setup.py test;
+after_success:
+  - conda env export
